#!/bin/bash

#this script needs the following variables to be defined
#TL_USER=username for the PC console
#TL_PASS=corresponding password
#TL_CONSOLE=PC console address

#create evilpetclinic collection
curl -k -u $TL_USER:$TL_PASS -H 'Content-Type: application/json' -X POST \
  -d '{"name":"evilpetclinic","containers":["*"],"hosts":["*"],"images":["*evilpetclinic*"],"labels":["*"],"appIDs":["*"],"functions":["*"],"namespaces":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"color":"#68DCFC"}' \
  https://$TL_CONSOLE/api/v1/collections

#code repo vuln
curl -k -u $TL_USER:$TL_PASS "https://$TL_CONSOLE/api/v1/policies/vulnerability/ci/images?project=Central+Console" \
  -X 'PUT' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-raw '{"rules":[{"modified":"2021-05-23T08:31:16.541Z","owner":"prussiello_paloaltonetworks_com","name":"fail on critical","previousName":"fail on critical","disabled":false,"effect":"alert, block","collections":[{"hosts":["*"],"images":["*evilpetclinic*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"evilpetclinic","owner":"prussiello_paloaltonetworks_com","modified":"2021-05-10T08:07:36.402Z","color":"#68DCFC","system":false,"prisma":false}],"action":["*"],"condition":{"readonly":false,"device":"","vulnerabilities":[]},"group":["*"],"alertThreshold":{"disabled":false,"value":1},"blockThreshold":{"enabled":true,"value":7},"graceDays":0,"license":{"alertThreshold":{"enabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0}},"verbose":false,"allCompliance":false,"onlyFixed":false,"cveRules":[],"tags":[],"notes":""},{"modified":"2021-05-09T14:10:26.957Z","owner":"system","name":"Default - alert all components","previousName":"","effect":"alert","collections":[{"hosts":["*"],"images":["*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"All","owner":"system","modified":"2021-05-09T14:10:28.076Z","color":"#3FA2F7","description":"System - all resources collection","system":true,"prisma":false}],"condition":{"readonly":false,"device":"","vulnerabilities":[]},"alertThreshold":{"disabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0},"graceDays":0,"license":{"alertThreshold":{"enabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0}}}],"policyType":"ciImagesVulnerability","_id":"ciImagesVulnerability","type":"vulnerability","policyContext":"ciImages"}' \


#code repo license compliance
curl -k -u $TL_USER:$TL_PASS "https://$TL_CONSOLE/api/v1/policies/compliance/ci/coderepos?project=Central+Console" \
  -X 'PUT' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-raw '{"rules":[{"modified":"2021-05-24T08:07:51.787Z","owner":"prussiello_paloaltonetworks_com","name":"fail on WTFPL","previousName":"fail on WTFPL","disabled":false,"effect":"alert, block","collections":[{"hosts":["*"],"images":["*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"All","owner":"system","modified":"2021-05-09T14:10:28.076Z","color":"#3FA2F7","description":"System - all resources collection","system":true,"prisma":false}],"condition":{"readonly":false,"device":"","vulnerabilities":[]},"alertThreshold":{"disabled":false,"value":1},"blockThreshold":{"enabled":false,"value":0},"graceDays":0,"license":{"alertThreshold":{"enabled":true,"value":1},"blockThreshold":{"enabled":true,"value":9},"critical":["WTFPL"],"high":["GPL-1.0","GPL-2.0","GPL-3.0","LGPL-2.1","LGPL-3.0","AGPL-3.0","AGPL-3.0-or-later","GPL-2.0-with-classpath-exception","EUPL-1.0","EUPL-1.1","EUPL-1.2"],"medium":["Artistic-1.0-Perl","EPL-1.0","MS-PL","MPL-1.0","MPL-1.1","MPL-2.0","CDDL-1.0","CDDL-1.1","CPAL-1.0","CPL-1.0","IPL-1.0","NPL-1.0","NPL-1.1"],"low":["MIT","Apache-1.0","Apache-1.1","Apache-2.0","BSD-3-Clause","ISC","BSD-2-Clause","CPOL-1.02","WTFPL","Zlib","ANTLR-PD","ICU","Info-ZIP"]},"verbose":false,"allCompliance":false,"onlyFixed":false,"cveRules":[],"tags":[]},{"modified":"2021-05-20T08:26:04.999Z","owner":"prussiello_paloaltonetworks_com","name":"Default - alert all components","previousName":"","effect":"alert","collections":[{"hosts":["*"],"images":["*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"All","owner":"system","modified":"2021-05-09T14:10:28.076Z","color":"#3FA2F7","description":"System - all resources collection","system":true,"prisma":false}],"condition":{"readonly":false,"device":"","vulnerabilities":[]},"alertThreshold":{"disabled":false,"value":1},"blockThreshold":{"enabled":false,"value":0},"graceDays":0,"license":{"alertThreshold":{"enabled":true,"value":1},"blockThreshold":{"enabled":false,"value":0},"critical":["MIT"],"high":["GPL-1.0","GPL-2.0","GPL-3.0","LGPL-2.1","LGPL-3.0","AGPL-3.0","AGPL-3.0-or-later","GPL-2.0-with-classpath-exception","EUPL-1.0","EUPL-1.1","EUPL-1.2"],"medium":["Artistic-1.0-Perl","EPL-1.0","MS-PL","MPL-1.0","MPL-1.1","MPL-2.0","CDDL-1.0","CDDL-1.1","CPAL-1.0","CPL-1.0","IPL-1.0","NPL-1.0","NPL-1.1"],"low":["MIT","Apache-1.0","Apache-1.1","Apache-2.0","BSD-3-Clause","ISC","BSD-2-Clause","CPOL-1.02","WTFPL","Zlib","ANTLR-PD","ICU","Info-ZIP"]}}],"policyType":"ciCodeRepoCompliance","_id":"ciCodeRepoCompliance","type":"compliance","policyContext":"ciCoderepos"}' 
  
#CI Container compliance
curl -k -u $TL_USER:$TL_PASS "https://$TL_CONSOLE/api/v1/policies/compliance/ci/images?project=Central+Console" \
  -X 'PUT' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-raw '{"rules":[{"modified":"2021-05-23T08:33:37.547Z","owner":"prussiello_paloaltonetworks_com","name":"Fail on malware","previousName":"Fail on malware","disabled":false,"effect":"alert, block","collections":[{"hosts":["*"],"images":["*evilpetclinic*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"evilpetclinic","owner":"prussiello_paloaltonetworks_com","modified":"2021-05-10T08:07:36.402Z","color":"#68DCFC","system":false,"prisma":false}],"action":["*"],"condition":{"readonly":false,"device":"","vulnerabilities":[{"id":41,"block":false},{"id":422,"block":true},{"id":424,"block":false},{"id":425,"block":false},{"id":426,"block":false},{"id":448,"block":false},{"id":5041,"block":false}]},"group":["*"],"alertThreshold":{"disabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0},"graceDays":0,"license":{"alertThreshold":{"enabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0}},"verbose":false,"allCompliance":false,"onlyFixed":false,"cveRules":[],"tags":[]},{"modified":"2021-05-09T14:10:26.957Z","owner":"system","name":"Default - alert on critical and high","previousName":"","effect":"alert","collections":[{"hosts":["*"],"images":["*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"All","owner":"system","modified":"2021-05-09T14:10:28.076Z","color":"#3FA2F7","description":"System - all resources collection","system":true,"prisma":false}],"condition":{"readonly":false,"device":"","vulnerabilities":[{"id":424,"block":false},{"id":425,"block":false},{"id":448,"block":false},{"id":422,"block":false},{"id":426,"block":false},{"id":5041,"block":false},{"id":41,"block":false}]},"alertThreshold":{"disabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0},"graceDays":0,"license":{"alertThreshold":{"enabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0}}}],"policyType":"ciImagesCompliance","_id":"ciImagesCompliance","type":"compliance","policyContext":"ciImages"}' 

