#code repo vuln
curl -u $TL_USER:$TL_PASS 'https://$TL_CONSOLE/api/v1/policies/vulnerability/ci/images?project=Central+Console' \
  -X 'PUT' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-raw '{"rules":[{"modified":"2021-05-23T08:31:16.541Z","owner":"prussiello_paloaltonetworks_com","name":"fail on critical","previousName":"fail on critical","disabled":false,"effect":"alert, block","collections":[{"hosts":["*"],"images":["*evilpetclinic*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"evilpetclinic","owner":"prussiello_paloaltonetworks_com","modified":"2021-05-10T08:07:36.402Z","color":"#68DCFC","system":false,"prisma":false}],"action":["*"],"condition":{"readonly":false,"device":"","vulnerabilities":[]},"group":["*"],"alertThreshold":{"disabled":false,"value":1},"blockThreshold":{"enabled":true,"value":7},"graceDays":0,"license":{"alertThreshold":{"enabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0}},"verbose":false,"allCompliance":false,"onlyFixed":false,"cveRules":[],"tags":[],"notes":""},{"modified":"2021-05-09T14:10:26.957Z","owner":"system","name":"Default - alert all components","previousName":"","effect":"alert","collections":[{"hosts":["*"],"images":["*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"All","owner":"system","modified":"2021-05-09T14:10:28.076Z","color":"#3FA2F7","description":"System - all resources collection","system":true,"prisma":false}],"condition":{"readonly":false,"device":"","vulnerabilities":[]},"alertThreshold":{"disabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0},"graceDays":0,"license":{"alertThreshold":{"enabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0}}}],"policyType":"ciImagesVulnerability","_id":"ciImagesVulnerability","type":"vulnerability","policyContext":"ciImages"}' \


#code repo license compliance


#CI Container compliance
curl 'https://$TL_CONSOLE/api/v1/policies/compliance/ci/images?project=Central+Console' \
  -X 'PUT' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicHJ1c3NpZWxsb19wYWxvYWx0b25ldHdvcmtzX2NvbSIsInJvbGUiOiJhZG1pbiIsImdyb3VwcyI6WyJhZG1pbnMiLCJkZXZvcHMiXSwicm9sZVBlcm1zIjpbWzI1NSwyNTUsMjU1LDI1NSwyNTUsMTI3LDBdLFsyNTUsMjU1LDI1NSwyNTUsMjU1LDEyNywwXV0sInBlcm1pc3Npb25zIjpbeyJwcm9qZWN0IjoiQ2VudHJhbCBDb25zb2xlIn1dLCJzZXNzaW9uVGltZW91dFNlYyI6ODY0MDAsImV4cCI6MTYyMTg0NDk5OSwiaXNzIjoidHdpc3Rsb2NrIn0.HqWUzSyfSLgD-ojCTQewX0lzfJDSVV0IRVKYtuc6Qd0' \
  --data-raw '{"rules":[{"modified":"2021-05-23T08:33:37.547Z","owner":"prussiello_paloaltonetworks_com","name":"Fail on malware","previousName":"Fail on malware","disabled":false,"effect":"alert, block","collections":[{"hosts":["*"],"images":["*evilpetclinic*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"evilpetclinic","owner":"prussiello_paloaltonetworks_com","modified":"2021-05-10T08:07:36.402Z","color":"#68DCFC","system":false,"prisma":false}],"action":["*"],"condition":{"readonly":false,"device":"","vulnerabilities":[{"id":41,"block":false},{"id":422,"block":true},{"id":424,"block":false},{"id":425,"block":false},{"id":426,"block":false},{"id":448,"block":false},{"id":5041,"block":false}]},"group":["*"],"alertThreshold":{"disabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0},"graceDays":0,"license":{"alertThreshold":{"enabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0}},"verbose":false,"allCompliance":false,"onlyFixed":false,"cveRules":[],"tags":[]},{"modified":"2021-05-09T14:10:26.957Z","owner":"system","name":"Default - alert on critical and high","previousName":"","effect":"alert","collections":[{"hosts":["*"],"images":["*"],"labels":["*"],"containers":["*"],"functions":["*"],"namespaces":["*"],"appIDs":["*"],"accountIDs":["*"],"codeRepos":["*"],"clusters":["*"],"name":"All","owner":"system","modified":"2021-05-09T14:10:28.076Z","color":"#3FA2F7","description":"System - all resources collection","system":true,"prisma":false}],"condition":{"readonly":false,"device":"","vulnerabilities":[{"id":424,"block":false},{"id":425,"block":false},{"id":448,"block":false},{"id":422,"block":false},{"id":426,"block":false},{"id":5041,"block":false},{"id":41,"block":false}]},"alertThreshold":{"disabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0},"graceDays":0,"license":{"alertThreshold":{"enabled":false,"value":0},"blockThreshold":{"enabled":false,"value":0}}}],"policyType":"ciImagesCompliance","_id":"ciImagesCompliance","type":"compliance","policyContext":"ciImages"}' \

